In [1]:
from UROP_matching import get_hs_code
import pandas as pd
import tqdm

In [2]:
# open the 1789HS.xlsx file
df = pd.read_excel('1789HS.xlsx')
# get all brief descriptions into a list
brief_descriptions = df['brief_description'].tolist()

len(brief_descriptions)

64

In [3]:
brief_descriptions[22]

# remove brief_descriptions[22] from brief_descriptions
brief_descriptions.remove(brief_descriptions[22])
len(brief_descriptions)

63

In [4]:
from tqdm import tqdm

# create a map between brief descriptions and HS codes using the get_hs_code function
brief_description_to_hs_code = {}
hs_code_to_product = {}
for brief_description in tqdm(brief_descriptions, desc="Processing brief descriptions"):
    # run the get_hs_code function at most 3 times if the function fails
    for i in range(3):
        try:
            hs_code, product = get_hs_code(brief_description)
            break
        except:
            continue
    brief_description_to_hs_code[brief_description] = hs_code
    hs_code_to_product[hs_code] = product

Processing brief descriptions:   0%|          | 0/63 [00:00<?, ?it/s]

Clicked option: Undenatured
GPT response invalid. Picked fallback: < 80.0 %
Clicked option: Sugar Cane
No questions asked.

Processing brief descriptions:   2%|▏         | 1/63 [00:29<30:37, 29.64s/it]

Clicked option: Undenatured
GPT response invalid. Picked fallback: < 80.0 %
Clicked option: Other
Clicked option: Other
No questions asked.

Processing brief descriptions:   3%|▎         | 2/63 [00:56<28:45, 28.29s/it]

Error in click_most_relevant_option: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.204); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
0   chromedriver                        0x0000000104bf3184 cxxbridge1$str$ptr + 3626716
1   chromedriver                        0x0000000104beb9d4 cxxbridge1$str$ptr + 3596076
2   chromedriver                        0x0000000104658968 cxxbridge1$string$len + 89228
3   chromedriver                        0x000000010465d84c cxxbridge1$string$len + 109424
4   chromedriver                        0x000000010465f89c cxxbridge1$string$len + 117696
5   chromedriver                        0x000000010465f944 cxxbridge1$string$len + 117864
6   chromedriver                        0x0000000104697f14 cxxbridge1$string$len + 348728
7   chromedriver                        0x0000000104692ec8 cxxbridge1$string$len + 328172
8   chromedriver                        0x00000001046d65b4 cxxbridge1$string$len + 604376
9   chromedriver                        0x0000000104691568 cxxbridge1$string$len + 321676
10  chromedriver                        0x00000001046921b8 cxxbridge1$string$len + 324828
11  chromedriver                        0x0000000104bbe9ac cxxbridge1$str$ptr + 3411716
12  chromedriver                        0x0000000104bc1ccc cxxbridge1$str$ptr + 3424804
13  chromedriver                        0x0000000104ba586c cxxbridge1$str$ptr + 3308996
14  chromedriver                        0x0000000104bc258c cxxbridge1$str$ptr + 3427044
15  chromedriver                        0x0000000104b9709c cxxbridge1$str$ptr + 3249652
16  chromedriver                        0x0000000104bdc4b8 cxxbridge1$str$ptr + 3533328
17  chromedriver                        0x0000000104bdc634 cxxbridge1$str$ptr + 3533708
18  chromedriver                        0x0000000104beb648 cxxbridge1$str$ptr + 3595168
19  libsystem_pthread.dylib             0x000000018f53c2e4 _pthread_start + 136
20  libsystem_pthread.dylib             0x000000018f5370fc thread_start + 8

Clicked option: Cane
No questions asked.

Processing brief descriptions:   5%|▍         | 3/63 [01:14<23:22, 23.38s/it]

GPT response invalid. Picked fallback: > 10.0 L
No questions asked.

Processing brief descriptions:   6%|▋         | 4/63 [01:25<18:00, 18.31s/it]

Clicked option: Other
GPT response invalid. Picked fallback: > 2.0 L
No questions asked.

Processing brief descriptions:   8%|▊         | 5/63 [01:41<17:01, 17.61s/it]

Clicked option: Ale
No questions asked.

Processing brief descriptions:  10%|▉         | 6/63 [01:52<14:32, 15.30s/it]

Clicked option: Malt
No questions asked.

Processing brief descriptions:  11%|█         | 7/63 [02:04<13:24, 14.37s/it]

Clicked option: Other
No questions asked.

Processing brief descriptions:  13%|█▎        | 8/63 [02:14<11:55, 13.02s/it]

Clicked option: Cane
Clicked option: Solid Or Powder
Clicked option: Raw
GPT response invalid. Picked fallback: >= 93 Degree
No questions asked.

Processing brief descriptions:  14%|█▍        | 9/63 [02:48<17:28, 19.41s/it]

Clicked option: Other
Clicked option: Other
No questions asked.

Processing brief descriptions:  16%|█▌        | 10/63 [03:03<15:59, 18.11s/it]

Clicked option: Other
Clicked option: Other
No questions asked.

Processing brief descriptions:  17%|█▋        | 11/63 [03:17<14:44, 17.01s/it]

Clicked option: Coffee And Coffee Preparations
Clicked option: Bean
Clicked option: Other
No questions asked.

Processing brief descriptions:  19%|█▉        | 12/63 [03:39<15:36, 18.37s/it]

Clicked option: Bean
No questions asked.

Processing brief descriptions:  21%|██        | 13/63 [03:49<13:09, 15.78s/it]

No questions asked.

Processing brief descriptions:  22%|██▏       | 14/63 [03:53<10:02, 12.29s/it]

No questions asked.

Processing brief descriptions:  24%|██▍       | 15/63 [03:57<07:52,  9.85s/it]

Clicked option: Other
No questions asked.

Processing brief descriptions:  25%|██▌       | 16/63 [04:08<07:56, 10.14s/it]

Clicked option: Other
Clicked option: Bar, Cake Or Moulded Shape
Clicked option: Personal Care
No questions asked.

Processing brief descriptions:  27%|██▋       | 17/63 [04:34<11:20, 14.79s/it]

Clicked option: Footwear
Clicked option: Leather
Clicked option: Leather
Clicked option: Other
No questions asked.

Processing brief descriptions:  29%|██▊       | 18/63 [05:08<15:26, 20.60s/it]

Clicked option: Footwear
Clicked option: Leather
Clicked option: Other
Clicked option: Other
No questions asked.

Processing brief descriptions:  30%|███       | 19/63 [05:50<19:48, 27.01s/it]

Clicked option: Other
No questions asked.

Processing brief descriptions:  32%|███▏      | 20/63 [06:04<16:30, 23.04s/it]

Clicked option: Electric Cable
Clicked option: Other
Clicked option: Other
Clicked option: <= 1000 V
Clicked option: Electrical Connector
No questions asked.

Processing brief descriptions:  33%|███▎      | 21/63 [06:37<18:14, 26.05s/it]

Clicked option: Other
Clicked option: Textile Material
Filled '% Agave Fibre' with 0%
Filled '% Synthetic Fibre' with 100%
Filled '% Other' with 0%
Clicked on 'Accept' button/option.
Filled '% Polyethylene Or Polypropylene' with 0%
Filled '% Other Synthetic Fibre' with 100%
Clicked on 'Accept' button/option.
No questions asked.

Processing brief descriptions:  35%|███▍      | 22/63 [07:03<17:57, 26.27s/it]

Clicked option: Textile Material
Filled '% Agave Fibre' with 0%
Filled '% Synthetic Fibre' with 100%
Filled '% Other' with 0%
Clicked on 'Accept' button/option.
Filled '% Polyethylene Or Polypropylene' with 50%
Filled '% Other Synthetic Fibre' with 50%
Clicked on 'Accept' button/option.
No questions asked.

Processing brief descriptions:  37%|███▋      | 23/63 [07:21<15:44, 23.62s/it]

Clicked option: Non-Alloy Steel
Clicked option: In Primary Form
Clicked option: Other
No questions asked.

Processing brief descriptions:  38%|███▊      | 24/63 [07:44<15:21, 23.64s/it]

Clicked option: Sharp Fastener
Clicked option: Other
No questions asked.

Processing brief descriptions:  40%|███▉      | 25/63 [08:00<13:27, 21.24s/it]

No questions asked.

Processing brief descriptions:  41%|████▏     | 26/63 [08:05<10:01, 16.26s/it]

Clicked option: Manufactured Tobacco
Clicked option: Other
Clicked option: Other
Clicked option: Smoking
Clicked option: Other
No questions asked.

Processing brief descriptions:  43%|████▎     | 27/63 [08:39<12:59, 21.66s/it]

Clicked option: Other
Clicked option: Intended For Inhalation Without Combustion
No questions asked.

Processing brief descriptions:  44%|████▍     | 28/63 [08:54<11:30, 19.72s/it]

Clicked option: Colouring Matter Of Vegetable Or Animal Origin
No questions asked.

Processing brief descriptions:  46%|████▌     | 29/63 [09:04<09:32, 16.83s/it]

Clicked option: Carded Or Combed
Clicked option: Carded
No questions asked.

Processing brief descriptions:  48%|████▊     | 30/63 [09:23<09:37, 17.50s/it]

Clicked option: Lignite
Clicked option: Other
No questions asked.

Processing brief descriptions:  49%|████▉     | 31/63 [09:40<09:07, 17.10s/it]

Clicked option: Whole Or In Pieces
Clicked option: Other
No questions asked.

Processing brief descriptions:  51%|█████     | 32/63 [10:01<09:30, 18.39s/it]

Clicked option: Other
Clicked option: Other
No questions asked.

Processing brief descriptions:  52%|█████▏    | 33/63 [10:18<08:58, 17.96s/it]

Clicked option: Tea Derived From Thea
Clicked option: Black Or Fermented
GPT response invalid. Picked fallback: > 3.0 Kg
No questions asked.

Processing brief descriptions:  54%|█████▍    | 34/63 [10:42<09:30, 19.69s/it]

No questions asked.
No questions asked.

Processing brief descriptions:  56%|█████▌    | 35/63 [10:51<07:47, 16.71s/it]

No questions asked.
No questions asked.
No questions asked.

Processing brief descriptions:  57%|█████▋    | 36/63 [11:01<06:34, 14.62s/it]

No questions asked.
Clicked option: Tea Derived From Thea
Option 'The product description does not provide information about the weight of the product. However, since I need to choose one, I'll go with:

<= 3.0 Kg' not found among list items. Picking fallback.
No questions asked.

Processing brief descriptions:  59%|█████▊    | 37/63 [11:18<06:38, 15.31s/it]

No questions asked.
No questions asked.

Processing brief descriptions:  60%|██████    | 38/63 [11:28<05:39, 13.58s/it]

No questions asked.
Clicked option: Other
No questions asked.

Processing brief descriptions:  62%|██████▏   | 39/63 [11:40<05:19, 13.32s/it]

Clicked option: China, Stone And Earthern Ware As Part Of Camera, Measuring Or Testing Equipment, Precision Instrument
Clicked option: Other
No questions asked.

Processing brief descriptions:  63%|██████▎   | 40/63 [11:59<05:46, 15.07s/it]

Error in click_most_relevant_option: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.204); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
0   chromedriver                        0x00000001011c7184 cxxbridge1$str$ptr + 3626716
1   chromedriver                        0x00000001011bf9d4 cxxbridge1$str$ptr + 3596076
2   chromedriver                        0x0000000100c2c968 cxxbridge1$string$len + 89228
3   chromedriver                        0x0000000100c3184c cxxbridge1$string$len + 109424
4   chromedriver                        0x0000000100c3389c cxxbridge1$string$len + 117696
5   chromedriver                        0x0000000100c33944 cxxbridge1$string$len + 117864
6   chromedriver                        0x0000000100c6bf14 cxxbridge1$string$len + 348728
7   chromedriver                        0x0000000100c66ec8 cxxbridge1$string$len + 328172
8   chromedriver                        0x0000000100caa5b4 cxxbridge1$string$len + 604376
9   chromedriver                        0x0000000100c65568 cxxbridge1$string$len + 321676
10  chromedriver                        0x0000000100c661b8 cxxbridge1$string$len + 324828
11  chromedriver                        0x00000001011929ac cxxbridge1$str$ptr + 3411716
12  chromedriver                        0x0000000101195ccc cxxbridge1$str$ptr + 3424804
13  chromedriver                        0x000000010117986c cxxbridge1$str$ptr + 3308996
14  chromedriver                        0x000000010119658c cxxbridge1$str$ptr + 3427044
15  chromedriver                        0x000000010116b09c cxxbridge1$str$ptr + 3249652
16  chromedriver                        0x00000001011b04b8 cxxbridge1$str$ptr + 3533328
17  chromedriver                        0x00000001011b0634 cxxbridge1$str$ptr + 3533708
18  chromedriver                        0x00000001011bf648 cxxbridge1$str$ptr + 3595168
19  libsystem_pthread.dylib             0x000000018f53c2e4 _pthread_start + 136
20  libsystem_pthread.dylib             0x000000018f5370fc thread_start + 8

Processing brief descriptions:  65%|██████▌   | 41/63 [12:06<04:34, 12.48s/it]

Clicked option: Put Up For Retail Sale
Clicked option: Other
No questions asked.

Processing brief descriptions:  67%|██████▋   | 42/63 [12:28<05:21, 15.31s/it]

Clicked option: Fastener For Fastening Together Two Ends Of A Belt Or Strap
Clicked option: Garment, Footwear, Awning, Handbag, Luggage, Tent Or Sail
Clicked option: Base Metal
No questions asked.

Processing brief descriptions:  68%|██████▊   | 43/63 [12:54<06:12, 18.62s/it]

Clicked option: Hand Made
No questions asked.

Processing brief descriptions:  70%|██████▉   | 44/63 [13:06<05:17, 16.73s/it]

No questions asked.

Processing brief descriptions:  71%|███████▏  | 45/63 [13:11<03:53, 12.99s/it]

Clicked option: Other
Clicked option: Other
No questions asked.

Processing brief descriptions:  73%|███████▎  | 46/63 [13:27<03:58, 14.01s/it]

Clicked option: Other
Clicked option: Other
Clicked option: >= 40 And <= 150 G/M2
Clicked option: Other
No questions asked.

Processing brief descriptions:  75%|███████▍  | 47/63 [14:09<05:59, 22.47s/it]

Clicked option: Furniture
Clicked option: Other
Clicked option: Designed For Placing On The Floor
Clicked option: Wood
Clicked option: Other
No questions asked.

Processing brief descriptions:  76%|███████▌  | 48/63 [15:06<08:12, 32.84s/it]

Clicked option: Apparel Fastening Or Decorating Article
Clicked option: Other
No questions asked.

Processing brief descriptions:  78%|███████▊  | 49/63 [15:23<06:33, 28.09s/it]

Clicked option: Saddlery
No questions asked.

Processing brief descriptions:  79%|███████▉  | 50/63 [15:33<04:54, 22.63s/it]

Clicked option: Other
No questions asked.

Processing brief descriptions:  81%|████████  | 51/63 [15:45<03:53, 19.47s/it]

Clicked option: Other
Clicked option: Furskin
No questions asked.

Processing brief descriptions:  83%|████████▎ | 52/63 [16:07<03:39, 19.97s/it]

No questions asked.
No questions asked.

Processing brief descriptions:  84%|████████▍ | 53/63 [16:16<02:48, 16.84s/it]

No questions asked.
Clicked option: Castings Of Iron, And Upslit And Rolled Iron As Part Of Machinery And Mechanical Appliances
Clicked option: Other
GPT response invalid. Picked fallback: Electronic Integrated Circuit
No questions asked.

Processing brief descriptions:  86%|████████▌ | 54/63 [16:46<03:06, 20.73s/it]

Clicked option: Bovine Or Equine
Clicked option: In The Dry State
Clicked option: Other
No questions asked.

Processing brief descriptions:  87%|████████▋ | 55/63 [17:11<02:56, 22.12s/it]

No questions asked.

Processing brief descriptions:  89%|████████▉ | 56/63 [17:16<01:57, 16.83s/it]

Clicked option: Other
Clicked option: Other
Clicked option: Other
Clicked option: Other
Clicked option: Other
Filled '% Cotton' with 33%
Filled '% Man-Made Fibre' with 33%
Filled '% Other' with 34%
Clicked on 'Accept' button/option.
No questions asked.

Processing brief descriptions:  90%|█████████ | 57/63 [18:00<02:29, 24.96s/it]

Clicked option: Article For Use At Home, Work Or School
Clicked option: Other
Clicked option: Cosmetic Or Artistic Purposes
No questions asked.

Processing brief descriptions:  92%|█████████▏| 58/63 [18:26<02:07, 25.46s/it]

Clicked option: Silver
No questions asked.

Processing brief descriptions:  94%|█████████▎| 59/63 [18:39<01:26, 21.69s/it]

Clicked option: Ground Tackle
No questions asked.

Processing brief descriptions:  95%|█████████▌| 60/63 [18:52<00:57, 19.06s/it]

Error in click_most_relevant_option: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.204); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
0   chromedriver                        0x0000000100c7f184 cxxbridge1$str$ptr + 3626716
1   chromedriver                        0x0000000100c779d4 cxxbridge1$str$ptr + 3596076
2   chromedriver                        0x00000001006e4968 cxxbridge1$string$len + 89228
3   chromedriver                        0x00000001006e984c cxxbridge1$string$len + 109424
4   chromedriver                        0x00000001006eb89c cxxbridge1$string$len + 117696
5   chromedriver                        0x00000001006eb944 cxxbridge1$string$len + 117864
6   chromedriver                        0x0000000100723f14 cxxbridge1$string$len + 348728
7   chromedriver                        0x000000010071eec8 cxxbridge1$string$len + 328172
8   chromedriver                        0x00000001007625b4 cxxbridge1$string$len + 604376
9   chromedriver                        0x000000010071d568 cxxbridge1$string$len + 321676
10  chromedriver                        0x000000010071e1b8 cxxbridge1$string$len + 324828
11  chromedriver                        0x0000000100c4a9ac cxxbridge1$str$ptr + 3411716
12  chromedriver                        0x0000000100c4dccc cxxbridge1$str$ptr + 3424804
13  chromedriver                        0x0000000100c3186c cxxbridge1$str$ptr + 3308996
14  chromedriver                        0x0000000100c4e58c cxxbridge1$str$ptr + 3427044
15  chromedriver                        0x0000000100c2309c cxxbridge1$str$ptr + 3249652
16  chromedriver                        0x0000000100c684b8 cxxbridge1$str$ptr + 3533328
17  chromedriver                        0x0000000100c68634 cxxbridge1$str$ptr + 3533708
18  chromedriver                        0x0000000100c77648 cxxbridge1$str$ptr + 3595168
19  libsystem_pthread.dylib             0x000000018f53c2e4 _pthread_start + 136
20  libsystem_pthread.dylib             0x000000018f5370fc thread_start + 8

Processing brief descriptions:  97%|█████████▋| 61/63 [18:59<00:30, 15.36s/it]

Clicked option: Other
Clicked option: Transportation
Clicked option: < 10.0 Persons
Clicked option: Other
Clicked option: Other
Clicked option: Other
No questions asked.

Processing brief descriptions:  98%|█████████▊| 62/63 [19:52<00:26, 26.67s/it]

No questions asked.
No questions asked.

Processing brief descriptions: 100%|██████████| 63/63 [20:02<00:00, 19.08s/it]

No questions asked.

In [8]:
# export brief_description_to_hs_code to a pickle file
import pickle

with open('brief_description_to_hs_code.pickle', 'wb') as handle:
    pickle.dump(brief_description_to_hs_code, handle, protocol=pickle.HIGHEST_PROTOCOL)

# export hs_code_to_product to a pickle file
with open('hs_code_to_product.pickle', 'wb') as handle:
    pickle.dump(hs_code_to_product, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [13]:
brief_description_to_hs_code

{'distilled spirits of Jamaica proof': '2208.40',
 'other distilled spirits': '22.08',
 'molasses': '17.03',
 'Madeira wine': '2204.29',
 'all other wines': '22.05',
 'beer, ale, or porter in casks': '2203.00.0000',
 'cider, beer, ale or porter in bottles': '2203.00.0000',
 'malt': '11.07',
 'brown sugars': '17.01',
 'loaf sugars': '17.02',
 'other sugars': '17.02',
 'coffee': '09.01',
 'cocoa': '1801.00.0000',
 'candles of tallow': '3406.00.0000',
 'candles of wax or spermaceti': '3406.00.0000',
 'cheese': '04.06',
 'soap': '34.01',
 'boots': '64.03',
 'shoes, slippers or goloshoes made of leather': '64.03',
 'shoes or slippers made of silk or stuff': '6405.20.1500',
 'cables': '85.44',
 'tarred cordage': '56.07',
 'twine or packthread': '56.07',
 'steel unwrought': '72.06',
 'nails and spikes': '9601.90.0000',
 'salt': '2501.00.0000',
 'manufactured tobacco': '24.03',
 'snuff': '24.04',
 'indigo': '3203.00.0000',
 'wool and cottcards': '51.05',
 'coal': '27.02',
 'pickled fish': '16.04',
 'dried fish': '03.05',
 'bohea tea': '09.02',
 'souchong': '09.02',
 'hyson': '09.02',
 'other green teas': '0902.20.0000',
 'other goods': '0902.20.0000',
 'looking-glasses, window and other glass': '90.04',
 'China, stone and earthern ware': 'None of the provided HS codes are appropriate for the product description "China, stone and earthern ware".',
 'gunpowder': '3601.00.0000',
 'paints ground in oil': '32.13',
 'shoe and knee buckles': '8308.90.6000',
 'gold and silver lace': '58.04',
 'gold and silver leaf': '71.06',
 'blank books': '4901.99',
 'writing, printing or wrapping paper, paper-hangings, pasteboard': '48.02',
 'cabinet wares': '94.03',
 'buttons': '96.06',
 'saddles': '42.01',
 'gloves of leather': '4203.29.0000',
 'hats of beaver, fur, wool, or mixture of either': '6506.99',
 'millinery ready made': '6506.99',
 'castings of iron, and upslit and rolled iron': 'The product description does not match the provided HS code options. Please provide relevant HS code options.',
 'leather tanned or tawed, and manufacture of leather': '41.04',
 'canes, walking sticks and whips': '6602.00.0000',
 'clothing ready made': '62.11',
 'brushes': '96.03',
 'gold, silver, and plated ware, and jewelry and paste work': '71.13',
 'anchors, and wrought, tin, and pewter ware,': '8007.00.9000',
 'playing cards': '9504.40.0000',
 'every coach, chariot or other four wheel carriage, and every chaise, solo, or other two wheel car, or parts thereof': '8703.90.0100',
 'other goods, wares and merchandise': '8703.90.0100'}

In [15]:
# brief_description_to_hs_code has the brief_description as the key and the hs_code as the value
# need to add a column to df called new_hs and fill it with the hs_code values given the brief_description from the brief_description_to_hs_code dictionary
df['new_hs'] = df['brief_description'].map(brief_description_to_hs_code)

# make a new column called new_product and fill it with the product values given the hs_code from the hs_code_to_product dictionary
df['new_product'] = df['new_hs'].map(hs_code_to_product)

# only keep columns year, hs, brief_description, new_hs, new_product from df
new_df = df[['year', 'hs', 'brief_description', 'new_hs', 'new_product']]

In [22]:
# need to fix the new_product column. each entry in that column follows format [hs_code: product]. need to just extract the product
# remove new_product2 from new_df
new_df = new_df.drop(columns=['new_product2'])

In [24]:
# export new_df as a pickle file
import pickle
with open('new_df.pkl', 'wb') as f:
    pickle.dump(new_df, f)

In [25]:
new_df

,year,hs,brief_description,new_hs,new_product
0,1789,22,distilled spirits of Jamaica proof,2208.40,[2208.40: -\nRum and other spirits obtained by...
1,1789,22,other distilled spirits,22.08,[22.08: Undenatured ethyl alcohol of an alcoho...
2,1789,17,molasses,17.03,[17.03: Molasses resulting from the extraction...
3,1789,22,Madeira wine,2204.29,[2204.29: - -\nOther:]
4,1789,22,all other wines,22.05,[22.05: Vermouth and other wine of fresh grape...
...,...,...,...,...,...
59,1789,71,"gold, silver, and plated ware, and jewelry and...",71.13,"[71.13: Articles of jewelry and parts thereof,..."
60,1789,83,"anchors, and wrought, tin, and pewter ware,",8007.00.9000,[8007.00.9000: -\nOther]
61,1789,95,playing cards,9504.40.0000,[9504.40.0000: -\nPlaying cards]
62,1789,87,"every coach, chariot or other four wheel carri...",8703.90.0100,[8703.90.0100: -\nOther]
63,1789,96,"other goods, wares and merchandise",8703.90.0100,[8703.90.0100: -\nOther]

In [36]:
new_df["new_product"].iloc[0]

['2208.40: -\nRum and other spirits obtained by distilling fermented sugar-cane products:',
 '2208.40.0030: - -\nIn containers each holding not over 4 liters',
 '2208.40.0050: - -\nIn containers each holding over 4 liters']

In [41]:
# for each entry in the new_product column in the new_df, get only the first item of the list and put it in new_product2
new_df

,year,hs,brief_description,new_hs,new_product
0,1789,22,distilled spirits of Jamaica proof,2208.40,[2208.40: -\nRum and other spirits obtained by...
1,1789,22,other distilled spirits,22.08,[22.08: Undenatured ethyl alcohol of an alcoho...
2,1789,17,molasses,17.03,[17.03: Molasses resulting from the extraction...
3,1789,22,Madeira wine,2204.29,[2204.29: - -\nOther:]
4,1789,22,all other wines,22.05,[22.05: Vermouth and other wine of fresh grape...
...,...,...,...,...,...
59,1789,71,"gold, silver, and plated ware, and jewelry and...",71.13,"[71.13: Articles of jewelry and parts thereof,..."
60,1789,83,"anchors, and wrought, tin, and pewter ware,",8007.00.9000,[8007.00.9000: -\nOther]
61,1789,95,playing cards,9504.40.0000,[9504.40.0000: -\nPlaying cards]
62,1789,87,"every coach, chariot or other four wheel carri...",8703.90.0100,[8703.90.0100: -\nOther]
63,1789,96,"other goods, wares and merchandise",8703.90.0100,[8703.90.0100: -\nOther]

In [42]:
new_df['new_product2'] = new_df['new_product'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)

In [48]:
# each entry in new_product2 is represented as a string where it is 'hs_code: product'. We just want the product after the :
# add the product in a new column

new_df['new_product2'] = new_df['new_product2'].apply(lambda x: x.split(': ')[1] if x is not None else None)

In [51]:
new_df

,year,hs,brief_description,new_hs,new_product,new_product2
0,1789,22,distilled spirits of Jamaica proof,2208.40,[2208.40: -\nRum and other spirits obtained by...,-\nRum and other spirits obtained by distillin...
1,1789,22,other distilled spirits,22.08,[22.08: Undenatured ethyl alcohol of an alcoho...,Undenatured ethyl alcohol of an alcoholic stre...
2,1789,17,molasses,17.03,[17.03: Molasses resulting from the extraction...,Molasses resulting from the extraction or refi...
3,1789,22,Madeira wine,2204.29,[2204.29: - -\nOther:],- -\nOther:
4,1789,22,all other wines,22.05,[22.05: Vermouth and other wine of fresh grape...,Vermouth and other wine of fresh grapes flavor...
...,...,...,...,...,...,...
59,1789,71,"gold, silver, and plated ware, and jewelry and...",71.13,"[71.13: Articles of jewelry and parts thereof,...","Articles of jewelry and parts thereof, of prec..."
60,1789,83,"anchors, and wrought, tin, and pewter ware,",8007.00.9000,[8007.00.9000: -\nOther],-\nOther
61,1789,95,playing cards,9504.40.0000,[9504.40.0000: -\nPlaying cards],-\nPlaying cards
62,1789,87,"every coach, chariot or other four wheel carri...",8703.90.0100,[8703.90.0100: -\nOther],-\nOther
63,1789,96,"other goods, wares and merchandise",8703.90.0100,[8703.90.0100: -\nOther],-\nOther

In [56]:
# delete the new_product and new_product3 column
new_df = new_df.drop(columns=['new_product', 'new_product3'])

# rename the new_product2 column to new_product
new_df = new_df.rename(columns={'new_product2': 'new_product'})

In [58]:
# convert the new_df to a pickle file
import pickle
with open('new_df.pkl', 'wb') as f:
    pickle.dump(new_df, f)

In [60]:
new_df

,year,hs,brief_description,new_hs,new_product
0,1789,22,distilled spirits of Jamaica proof,2208.40,-\nRum and other spirits obtained by distillin...
1,1789,22,other distilled spirits,22.08,Undenatured ethyl alcohol of an alcoholic stre...
2,1789,17,molasses,17.03,Molasses resulting from the extraction or refi...
3,1789,22,Madeira wine,2204.29,- -\nOther:
4,1789,22,all other wines,22.05,Vermouth and other wine of fresh grapes flavor...
...,...,...,...,...,...
59,1789,71,"gold, silver, and plated ware, and jewelry and...",71.13,"Articles of jewelry and parts thereof, of prec..."
60,1789,83,"anchors, and wrought, tin, and pewter ware,",8007.00.9000,-\nOther
61,1789,95,playing cards,9504.40.0000,-\nPlaying cards
62,1789,87,"every coach, chariot or other four wheel carri...",8703.90.0100,-\nOther
63,1789,96,"other goods, wares and merchandise",8703.90.0100,-\nOther

In [68]:
# run f1 score for 2 digit between column hs and new_hs
# the value for a given row should be 1 if the first 2 digits of hs and new_hs are the same, 0 otherwise
# add a column to the new_df called f1

# first, we need to make sure the numbers in hs are two digits. if not, we need to add a 0 in front of the number
new_df['hs'] = new_df['hs'].apply(lambda x: '0' + str(x) if len(str(x)) == 1 else str(x))

new_df['f1'] = new_df.apply(lambda row: 1 if str(row['hs'])[:2] == str(row['new_hs'])[:2] else 0, axis=1)

In [72]:
f1_score = new_df['f1'].sum() / (len(new_df) -1)

f1_score

0.7619047619047619