In [18]:
import pandas as pd
import torch
import pickle
import os
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed

from transformers import AutoTokenizer, AutoModel

In [20]:
import pandas as pd

# 1. Load the CSV (either from local file or raw GitHub URL)
#    If you want to fetch directly, use the raw URL below; 
#    otherwise replace with 'harmonized-system.csv'.
url = 'https://raw.githubusercontent.com/datasets/harmonized-system/main/data/harmonized-system.csv'
df = pd.read_csv(url, dtype=str)


# get all of the rows that have level 2
chapters = df[df['level'] == str(2)]
headings = df[df['level'] == str(4)]
subheadings = df[df['level'] == str(6)]


chapters

,section,hscode,description,parent,level
0,I,01,Animals; live,TOTAL,2
41,I,02,Meat and edible meat offal,TOTAL,2
118,I,03,"Fish and crustaceans, molluscs and other aquat...",TOTAL,2
353,I,04,Dairy produce; birds' eggs; natural honey; edi...,TOTAL,2
397,I,05,Animal originated products; not elsewhere spec...,TOTAL,2
...,...,...,...,...,...
6733,XX,94,"Furniture; bedding, mattresses, mattress suppo...",TOTAL,2
6794,XX,95,"Toys, games and sports requisites; parts and a...",TOTAL,2
6840,XX,96,Miscellaneous manufactured articles,TOTAL,2
6910,XXI,97,Works of art; collectors' pieces and antiques,TOTAL,2
6936,TOTAL,99,Commodities not specified according to kind,TOTAL,2

In [13]:
all_tariffs = pd.read_csv('all_tariffs.csv')

# get 2023 data

all_tariffs = all_tariffs[all_tariffs['year'] == 2023]

all_tariffs

/var/folders/87/vb506yp95bn1dt3x5p9sbk4r0000gn/T/ipykernel_64090/1098268842.py:1: DtypeWarning: Columns (1,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  all_tariffs = pd.read_csv('all_tariffs.csv')

,year,hs,brief_description,mfn_ad_val_rate,mfn_specific_rate,unit_1,unit_2,quantity_1_code,quantity_2_code,description_1,...,country_1,country_duty_1,country_2,country_duty_2,country_3,country_duty_3,country_desc,country_codes,mfn_other_rate,mfn_rate_type_code
745524,2023,1012100,Live purebred breeding horses,0.000,0.0,NaN,NaN,NO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
745525,2023,1012900,Live horses other than purebred breeding horses,0.000,0.0,NaN,NaN,NO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
745526,2023,1013000,Live asses,0.068,0.0,NaN,NaN,NO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7
745527,2023,1019030,Mules and hinnies imported for immediate slaug...,0.000,0.0,NaN,NaN,NO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
745528,2023,1019040,Mules and hinnies not imported for immediate s...,0.045,0.0,NaN,NaN,NO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
758605,2023,99990061,Imports of wool apparel from Mexico described ...,NaN,NaN,NaN,NaN,SME,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758606,2023,99990062,Imports of textile and apparel goods from Mexi...,NaN,NaN,NaN,NaN,SME,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758607,2023,99990064,Imports of textile and apparel goods from Mexi...,NaN,NaN,NaN,NaN,SME,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758608,2023,99990084,Goods imported from Singapore and treated as o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758609,2023,99999500,Estimated imports of low valued transactions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X

In [4]:
def setup_model_and_tokenizer():
    token = 'REDACTED_HF_TOKEN'
    model_name = 'sentence-transformers/all-mpnet-base-v2'
    tokenizer = AutoTokenizer.from_pretrained(model_name, token=token)
    model = AutoModel.from_pretrained(model_name, token=token)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)
    model.eval()
    return tokenizer, model, device

In [5]:
def encode_text(texts, tokenizer, model, device, batch_size=64):
    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        encoded_input = tokenizer(batch, padding=True, truncation=True, return_tensors="pt")
        encoded_input = {k: v.to(device) for k, v in encoded_input.items()}
        with torch.no_grad():
            model_output = model(**encoded_input)
        token_embeddings = model_output.last_hidden_state
        attention_mask = encoded_input['attention_mask']
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, dim=1)
        sum_mask = torch.clamp(input_mask_expanded.sum(dim=1), min=1e-9)
        embeddings = sum_embeddings / sum_mask
        embeddings = torch.nn.functional.normalize(embeddings, p=2, dim=1)
        all_embeddings.append(embeddings.cpu())
    return torch.cat(all_embeddings, dim=0)

In [6]:
def process_year(year, df, tokenizer, model, device, output_dir):
    df_year = df[df['year'] == year]
    descriptions = df_year['brief_description'].tolist()
    if not descriptions:
        return None
    embeddings = encode_text(descriptions, tokenizer, model, device)
    embeddings_np = embeddings.cpu().numpy()
    out_path = os.path.join(output_dir, f'embeddings_{year}.pkl')
    with open(out_path, 'wb') as f:
        pickle.dump(embeddings_np, f)
    return out_path

In [7]:
df = pd.read_csv('all_tariffs.csv')
df = df.dropna(subset=['brief_description']).copy()
df['brief_description'] = df['brief_description'].astype(str)
years = sorted(df['year'].unique())
tokenizer, model, device = setup_model_and_tokenizer()
output_dir = '.'

/var/folders/87/vb506yp95bn1dt3x5p9sbk4r0000gn/T/ipykernel_49770/3295271234.py:1: DtypeWarning: Columns (1,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('all_tariffs.csv')

In [8]:
max_workers = min(32, (os.cpu_count() or 1) + 4)  # Dynamically set max_workers

with ThreadPoolExecutor(max_workers=max_workers) as executor:
    futures = {}
    for year in years:
        out_path = os.path.join(output_dir, f'embeddings_{year}.pkl')
        if os.path.exists(out_path):
            print(f"Already exists: {out_path}, skipping.")
            continue
        futures[executor.submit(process_year, year, df, tokenizer, model, device, output_dir)] = year

    for future in tqdm(as_completed(futures), total=len(futures), desc="Processing years"):
        year = futures[future]
        try:
            out_path = future.result()
            if out_path:
                print(f"Saved {out_path}")
        except Exception as e:
            print(f"Error processing year {year}: {e}")

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Already exists: ./embeddings_1789.pkl, skipping.
Already exists: ./embeddings_1790.pkl, skipping.
Already exists: ./embeddings_1792.pkl, skipping.
Already exists: ./embeddings_1816.pkl, skipping.
Already exists: ./embeddings_1824.pkl, skipping.
Already exists: ./embeddings_1828.pkl, skipping.
Already exists: ./embeddings_1846.pkl, skipping.
Already exists: ./embeddings_1861.pkl, skipping.
Already exists: ./embeddings_1883.pkl, skipping.
Already exists: ./embeddings_1894.pkl, skipping.
Already exists: ./embeddings_1897.pkl, skipping.
Already exists: ./embeddings_1913.pkl, skipping.
Already exists: ./embeddings_1922.pkl, skipping.

Processing years:   1%|          | 1/83 [34:51<47:38:01, 2091.24s/it]

Saved ./embeddings_1939.pkl

Processing years:   2%|▏         | 2/83 [35:14<19:40:46, 874.65s/it]

Saved ./embeddings_1934.pkl

Processing years:   4%|▎         | 3/83 [35:51<10:56:19, 492.24s/it]

Saved ./embeddings_1931.pkl

Processing years:   5%|▍         | 4/83 [36:18<6:46:19, 308.61s/it]

Saved ./embeddings_1935.pkl

Processing years:   6%|▌         | 5/83 [36:23<4:18:38, 198.96s/it]

Saved ./embeddings_1938.pkl

Processing years:   7%|▋         | 6/83 [36:23<2:48:51, 131.57s/it]

Saved ./embeddings_1937.pkl

Processing years:   8%|▊         | 7/83 [36:29<1:54:30, 90.40s/it]

Saved ./embeddings_1936.pkl

Processing years:  10%|▉         | 8/83 [36:33<1:18:28, 62.78s/it]

Saved ./embeddings_1933.pkl

Processing years:  11%|█         | 9/83 [36:44<57:36, 46.72s/it]

Saved ./embeddings_1932.pkl

Processing years:  12%|█▏        | 10/83 [36:58<44:23, 36.49s/it]

Saved ./embeddings_1941.pkl

Processing years:  13%|█▎        | 11/83 [37:00<31:09, 25.96s/it]

Saved ./embeddings_1940.pkl

Processing years:  14%|█▍        | 12/83 [37:14<26:39, 22.53s/it]

Saved ./embeddings_1930.pkl

Processing years:  16%|█▌        | 13/83 [58:24<7:47:12, 400.46s/it]

Saved ./embeddings_1953.pkl

Processing years:  17%|█▋        | 14/83 [1:01:58<6:35:39, 344.05s/it]

Saved ./embeddings_1942.pkl

Processing years:  18%|█▊        | 15/83 [1:05:04<5:35:44, 296.25s/it]

Saved ./embeddings_1943.pkl

Processing years:  19%|█▉        | 16/83 [1:07:26<4:39:09, 250.00s/it]

Saved ./embeddings_1944.pkl

Processing years:  20%|██        | 17/83 [1:09:44<3:57:55, 216.29s/it]

Saved ./embeddings_1952.pkl

Processing years:  22%|██▏       | 18/83 [1:09:56<2:47:42, 154.81s/it]

Saved ./embeddings_1945.pkl

Processing years:  23%|██▎       | 19/83 [1:10:10<1:59:55, 112.43s/it]

Saved ./embeddings_1947.pkl

Processing years:  24%|██▍       | 20/83 [1:10:18<1:25:08, 81.09s/it]

Saved ./embeddings_1946.pkl

Processing years:  25%|██▌       | 21/83 [1:10:33<1:03:30, 61.46s/it]

Saved ./embeddings_1949.pkl

Processing years:  27%|██▋       | 22/83 [1:10:37<44:48, 44.08s/it]

Saved ./embeddings_1948.pkl

Processing years:  29%|██▉       | 24/83 [1:11:05<27:02, 27.50s/it]

Saved ./embeddings_1951.pkl
Saved ./embeddings_1950.pkl

Processing years:  30%|███       | 25/83 [1:17:59<2:18:44, 143.53s/it]

Saved ./embeddings_1954.pkl

Processing years:  31%|███▏      | 26/83 [1:22:04<2:45:13, 173.91s/it]

Saved ./embeddings_1955.pkl

Processing years:  33%|███▎      | 27/83 [1:24:51<2:40:19, 171.77s/it]

Saved ./embeddings_1956.pkl

Processing years:  34%|███▎      | 28/83 [1:27:04<2:26:58, 160.34s/it]

Saved ./embeddings_1957.pkl

Processing years:  35%|███▍      | 29/83 [1:28:23<2:02:09, 135.74s/it]

Saved ./embeddings_1963.pkl

Processing years:  36%|███▌      | 30/83 [1:29:32<1:42:21, 115.89s/it]

Saved ./embeddings_1968.pkl

Processing years:  37%|███▋      | 31/83 [1:29:33<1:10:25, 81.25s/it]

Saved ./embeddings_1965.pkl

Processing years:  39%|███▊      | 32/83 [1:31:07<1:12:25, 85.21s/it]

Saved ./embeddings_1958.pkl

Processing years:  40%|███▉      | 33/83 [1:31:31<55:45, 66.90s/it]

Saved ./embeddings_1959.pkl

Processing years:  41%|████      | 34/83 [1:32:53<58:08, 71.20s/it]

Saved ./embeddings_1960.pkl

Processing years:  42%|████▏     | 35/83 [1:33:20<46:30, 58.14s/it]

Saved ./embeddings_1961.pkl

Processing years:  43%|████▎     | 36/83 [1:35:20<1:00:00, 76.60s/it]

Saved ./embeddings_1962.pkl

Processing years:  45%|████▍     | 37/83 [1:35:55<49:05, 64.04s/it]

Saved ./embeddings_1969.pkl

Processing years:  46%|████▌     | 38/83 [1:40:53<1:40:42, 134.28s/it]

Saved ./embeddings_1971.pkl

Processing years:  47%|████▋     | 39/83 [1:43:57<1:49:30, 149.33s/it]

Saved ./embeddings_1972.pkl

Processing years:  48%|████▊     | 40/83 [1:46:05<1:42:25, 142.91s/it]

Saved ./embeddings_1975.pkl

Processing years:  49%|████▉     | 41/83 [1:47:48<1:31:35, 130.84s/it]

Saved ./embeddings_1976.pkl

Processing years:  51%|█████     | 42/83 [1:49:28<1:23:05, 121.59s/it]

Saved ./embeddings_1978.pkl

Processing years:  52%|█████▏    | 43/83 [1:52:03<1:27:46, 131.67s/it]

Saved ./embeddings_1980.pkl

Processing years:  53%|█████▎    | 44/83 [1:54:29<1:28:27, 136.10s/it]

Saved ./embeddings_1981.pkl

Processing years:  54%|█████▍    | 45/83 [1:55:07<1:07:23, 106.41s/it]

Saved ./embeddings_1983.pkl

Processing years:  55%|█████▌    | 46/83 [1:57:35<1:13:21, 118.97s/it]

Saved ./embeddings_1984.pkl

Processing years:  57%|█████▋    | 47/83 [1:58:02<54:55, 91.54s/it]

Saved ./embeddings_1989.pkl

Processing years:  58%|█████▊    | 48/83 [1:58:40<43:57, 75.34s/it]

Saved ./embeddings_1985.pkl

Processing years:  59%|█████▉    | 49/83 [1:59:02<33:34, 59.24s/it]

Saved ./embeddings_1990.pkl

Processing years:  60%|██████    | 50/83 [2:00:10<34:09, 62.09s/it]

Saved ./embeddings_1987.pkl

Processing years:  61%|██████▏   | 51/83 [2:00:12<23:30, 44.08s/it]

Saved ./embeddings_1986.pkl

Processing years:  63%|██████▎   | 52/83 [2:01:30<27:56, 54.09s/it]

Saved ./embeddings_1991.pkl

Processing years:  64%|██████▍   | 53/83 [2:02:49<30:51, 61.73s/it]

Saved ./embeddings_1992.pkl

Processing years:  65%|██████▌   | 54/83 [2:04:05<31:49, 65.83s/it]

Saved ./embeddings_1993.pkl

Processing years:  66%|██████▋   | 55/83 [2:09:20<1:05:40, 140.72s/it]

Saved ./embeddings_1995.pkl

Processing years:  67%|██████▋   | 56/83 [2:11:11<59:13, 131.62s/it]

Saved ./embeddings_1996.pkl

Processing years:  69%|██████▊   | 57/83 [2:13:26<57:30, 132.73s/it]

Saved ./embeddings_1998.pkl

Processing years:  70%|██████▉   | 58/83 [2:14:21<45:35, 109.40s/it]

Saved ./embeddings_1997.pkl

Processing years:  71%|███████   | 59/83 [2:17:10<50:51, 127.14s/it]

Saved ./embeddings_2001.pkl

Processing years:  72%|███████▏  | 60/83 [2:17:51<38:54, 101.51s/it]

Saved ./embeddings_1999.pkl

Processing years:  73%|███████▎  | 61/83 [2:18:52<32:46, 89.39s/it]

Saved ./embeddings_2003.pkl

Processing years:  75%|███████▍  | 62/83 [2:19:48<27:47, 79.38s/it]

Saved ./embeddings_2004.pkl

Processing years:  76%|███████▌  | 63/83 [2:19:55<19:13, 57.70s/it]

Saved ./embeddings_2000.pkl

Processing years:  77%|███████▋  | 64/83 [2:21:52<23:54, 75.48s/it]

Saved ./embeddings_2002.pkl

Processing years:  78%|███████▊  | 65/83 [2:24:05<27:44, 92.50s/it]

Saved ./embeddings_2005.pkl

Processing years:  80%|███████▉  | 66/83 [2:32:06<59:15, 209.17s/it]

Saved ./embeddings_2007.pkl

Processing years:  81%|████████  | 67/83 [2:33:22<45:08, 169.31s/it]

Saved ./embeddings_2008.pkl

Processing years:  82%|████████▏ | 68/83 [2:36:05<41:51, 167.42s/it]

Saved ./embeddings_2010.pkl

Processing years:  83%|████████▎ | 69/83 [2:38:57<39:21, 168.71s/it]

Saved ./embeddings_2011.pkl

Processing years:  84%|████████▍ | 70/83 [2:39:34<28:00, 129.25s/it]

Saved ./embeddings_2015.pkl

Processing years:  86%|████████▌ | 71/83 [2:41:59<26:46, 133.87s/it]

Saved ./embeddings_2013.pkl

Processing years:  87%|████████▋ | 72/83 [2:42:38<19:20, 105.50s/it]

Saved ./embeddings_2014.pkl

Processing years:  88%|████████▊ | 73/83 [2:43:03<13:32, 81.30s/it]

Saved ./embeddings_2016.pkl

Processing years:  89%|████████▉ | 74/83 [2:43:52<10:44, 71.62s/it]

Saved ./embeddings_2017.pkl

Processing years:  90%|█████████ | 75/83 [2:45:00<09:24, 70.54s/it]

Saved ./embeddings_2009.pkl

Processing years:  92%|█████████▏| 76/83 [2:45:45<07:20, 62.99s/it]

Saved ./embeddings_2006.pkl

Processing years:  93%|█████████▎| 77/83 [2:49:29<11:06, 111.07s/it]

Saved ./embeddings_2018.pkl

Processing years:  94%|█████████▍| 78/83 [2:51:44<09:52, 118.48s/it]

Saved ./embeddings_2019.pkl

Processing years:  95%|█████████▌| 79/83 [2:52:43<06:42, 100.65s/it]

Saved ./embeddings_2021.pkl

Processing years:  96%|█████████▋| 80/83 [2:53:19<04:02, 80.97s/it]

Saved ./embeddings_2022.pkl

Processing years:  98%|█████████▊| 81/83 [2:53:42<02:07, 63.71s/it]

Saved ./embeddings_2023.pkl

Processing years:  99%|█████████▉| 82/83 [2:55:34<01:18, 78.34s/it]

Saved ./embeddings_2020.pkl

Processing years: 100%|██████████| 83/83 [2:56:27<00:00, 127.56s/it]

Saved ./embeddings_2012.pkl