In [31]:
import pandas as pd
import os

In [32]:
all_tariffs = pd.read_csv('all_tariffs.csv')
years = all_tariffs['year'].unique()
all_tariffs

/var/folders/87/vb506yp95bn1dt3x5p9sbk4r0000gn/T/ipykernel_34860/1533025050.py:1: DtypeWarning:

Columns (1,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26) have mixed types. Specify dtype option on import or set low_memory=False.

,year,hs,brief_description,mfn_ad_val_rate,mfn_specific_rate,unit_1,unit_2,quantity_1_code,quantity_2_code,description_1,...,country_1,country_duty_1,country_2,country_duty_2,country_3,country_duty_3,country_desc,country_codes,mfn_other_rate,mfn_rate_type_code
0,1789,NaN,distilled spirits of Jamaica proof,0.0,10,per gallon,NaN,NaN,NaN,imported from any kingdom of country whatsoever,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1789,NaN,other distilled spirits,0.0,8,per gallon,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1789,NaN,molasses,0.0,2.5,per gallon,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1789,NaN,Madeira wine,0.0,18,per gallon,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1789,NaN,all other wines,0.0,10,per gallon,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
758605,2023,99990061,Imports of wool apparel from Mexico described ...,NaN,NaN,NaN,NaN,SME,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758606,2023,99990062,Imports of textile and apparel goods from Mexi...,NaN,NaN,NaN,NaN,SME,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758607,2023,99990064,Imports of textile and apparel goods from Mexi...,NaN,NaN,NaN,NaN,SME,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758608,2023,99990084,Goods imported from Singapore and treated as o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
758609,2023,99999500,Estimated imports of low valued transactions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X

N -> N+1

In [33]:
# Directory containing the mapping files
mapping_dir = "./new_N_N1_mappings"

# Generate all possible filename pairs for consecutive years
mapping_dfs = []
for i in range(len(years)-1, 0, -1):
    y1, y2 = years[i], years[i-1]
    print(f"Processing mapping for years: {y2} to {y1}")
    filename = f"mapped_{y2}_{y1}.csv"
    filepath = os.path.join(mapping_dir, filename)
    if os.path.exists(filepath):
        df_map = pd.read_csv(filepath)
        df_map['from_year'] = y2
        df_map['to_year'] = y1
        df_map["year_N"] = y2
        df_map["year_N1"] = y1
        mapping_dfs.append(df_map)
    else:
        print(f"File {filename} does not exist in the directory {mapping_dir}. Skipping.")

# Concatenate all mapping dataframes
all_mappings_1 = pd.concat(mapping_dfs, ignore_index=True)

Processing mapping for years: 2022 to 2023
Processing mapping for years: 2021 to 2022
Processing mapping for years: 2020 to 2021
Processing mapping for years: 2019 to 2020
Processing mapping for years: 2018 to 2019
Processing mapping for years: 2017 to 2018
Processing mapping for years: 2016 to 2017
Processing mapping for years: 2015 to 2016
Processing mapping for years: 2014 to 2015
Processing mapping for years: 2013 to 2014
Processing mapping for years: 2012 to 2013
Processing mapping for years: 2011 to 2012
Processing mapping for years: 2010 to 2011
Processing mapping for years: 2009 to 2010
Processing mapping for years: 2008 to 2009
Processing mapping for years: 2007 to 2008
Processing mapping for years: 2006 to 2007
Processing mapping for years: 2005 to 2006
Processing mapping for years: 2004 to 2005
Processing mapping for years: 2003 to 2004
Processing mapping for years: 2002 to 2003
Processing mapping for years: 2001 to 2002
Processing mapping for years: 2000 to 2001
Processing mapping for years: 1999 to 2000
Processing mapping for years: 1998 to 1999
Processing mapping for years: 1997 to 1998
Processing mapping for years: 1996 to 1997
Processing mapping for years: 1995 to 1996
Processing mapping for years: 1993 to 1995
Processing mapping for years: 1992 to 1993
Processing mapping for years: 1991 to 1992
Processing mapping for years: 1990 to 1991
Processing mapping for years: 1989 to 1990
Processing mapping for years: 1987 to 1989
Processing mapping for years: 1986 to 1987
Processing mapping for years: 1985 to 1986
Processing mapping for years: 1984 to 1985
Processing mapping for years: 1983 to 1984
Processing mapping for years: 1981 to 1983
Processing mapping for years: 1980 to 1981
Processing mapping for years: 1978 to 1980
Processing mapping for years: 1976 to 1978
Processing mapping for years: 1975 to 1976
Processing mapping for years: 1972 to 1975
Processing mapping for years: 1971 to 1972
Processing mapping for years: 1969 to 1971
Processing mapping for years: 1968 to 1969
Processing mapping for years: 1965 to 1968
Processing mapping for years: 1963 to 1965
Processing mapping for years: 1962 to 1963
Processing mapping for years: 1961 to 1962
Processing mapping for years: 1960 to 1961
Processing mapping for years: 1959 to 1960
Processing mapping for years: 1958 to 1959
Processing mapping for years: 1957 to 1958
Processing mapping for years: 1956 to 1957
Processing mapping for years: 1955 to 1956
Processing mapping for years: 1954 to 1955
Processing mapping for years: 1953 to 1954
Processing mapping for years: 1952 to 1953
Processing mapping for years: 1951 to 1952
Processing mapping for years: 1950 to 1951
Processing mapping for years: 1949 to 1950
Processing mapping for years: 1948 to 1949
Processing mapping for years: 1947 to 1948
Processing mapping for years: 1946 to 1947
Processing mapping for years: 1945 to 1946
Processing mapping for years: 1944 to 1945
Processing mapping for years: 1943 to 1944
Processing mapping for years: 1942 to 1943
Processing mapping for years: 1941 to 1942
Processing mapping for years: 1940 to 1941
Processing mapping for years: 1939 to 1940
Processing mapping for years: 1938 to 1939
Processing mapping for years: 1937 to 1938
Processing mapping for years: 1936 to 1937
Processing mapping for years: 1935 to 1936
Processing mapping for years: 1934 to 1935
Processing mapping for years: 1933 to 1934
Processing mapping for years: 1932 to 1933
Processing mapping for years: 1931 to 1932
Processing mapping for years: 1930 to 1931
Processing mapping for years: 1922 to 1930
Processing mapping for years: 1913 to 1922
Processing mapping for years: 1897 to 1913
Processing mapping for years: 1894 to 1897
Processing mapping for years: 1883 to 1894
Processing mapping for years: 1861 to 1883
Processing mapping for years: 1846 to 1861
Processing mapping for years: 1828 to 1846
Processing mapping for years: 1824 to 1828
Processing mapping for years: 1816 to 1824
Processing mapping for years: 1792 to 1816
Processing mapping for years: 1790 to 1792
Processing mapping for years: 1789 to 1790

In [34]:
all_mappings_1

,HS_N1,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1
0,1023100,Live purebred breeding buffalo,1023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
1,1019040,Mules and hinnies not imported for immediate s...,1019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
2,1031000,Live purebred breeding swine,1031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
3,1022100,Live purebred breeding cattle,1022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
4,1012900,Live horses other than purebred breeding horses,1012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790

In [35]:
# rename HS_N1 to HS_N
all_mappings_1.rename(columns={"HS_N1": "HS_N"}, inplace=True)

In [36]:
all_mappings_1

,HS_N,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1
0,1023100,Live purebred breeding buffalo,1023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
1,1019040,Mules and hinnies not imported for immediate s...,1019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
2,1031000,Live purebred breeding swine,1031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
3,1022100,Live purebred breeding cattle,1022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
4,1012900,Live horses other than purebred breeding horses,1012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790

In [37]:
def clean_hs_codes(df, year_col='from_year', code_col='HS_N', year_threshold=1989):
    # Only modify rows where from_year >= year_threshold and HS_N1 is not null
    mask = (df[year_col] >= year_threshold) 
    # Convert to string
    df.loc[mask, code_col] = df.loc[mask, code_col].astype(str)
    # Remove trailing '.0' if present and length > 8
    df.loc[mask, code_col] = df.loc[mask, code_col].apply(lambda x: x[:-2] if len(x) > 8 and x.endswith('.0') else x)
    # Remove rows with 10-digit codes
    df = df[~((df[year_col] >= year_threshold) & (df[code_col].astype(str).str.len() >= 10))]
    # Add leading zero to 7-digit codes
    mask = (df[year_col] >= year_threshold) & (df[code_col].astype(str).str.len() == 7)
    df.loc[mask, code_col] = df.loc[mask, code_col].apply(lambda x: '0' + x)
    return df

all_mappings_1 = clean_hs_codes(all_mappings_1)

In [38]:
all_mappings_1

,HS_N,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1
0,01023100,Live purebred breeding buffalo,1023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
1,01019040,Mules and hinnies not imported for immediate s...,1019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
2,01031000,Live purebred breeding swine,1031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
3,01022100,Live purebred breeding cattle,1022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
4,01012900,Live horses other than purebred breeding horses,1012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790

In [39]:
df_1989_onwards = all_mappings_1[all_mappings_1['from_year'] >= 1989]

df_1989_onwards["HS_N"].astype(str).str.len().value_counts()

HS_N
8    459783
Name: count, dtype: int64

In [40]:
all_mappings_1

,HS_N,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1
0,01023100,Live purebred breeding buffalo,1023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
1,01019040,Mules and hinnies not imported for immediate s...,1019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
2,01031000,Live purebred breeding swine,1031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
3,01022100,Live purebred breeding cattle,1022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
4,01012900,Live horses other than purebred breeding horses,1012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023
...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790

In [41]:
def clean_hs_codes(df, year_col='to_year', code_col='Mapped_HS', year_threshold=1989):
    # Only modify rows where from_year >= year_threshold and HS_N1 is not null
    mask = (df[year_col] >= year_threshold) 
    # Convert to string
    df.loc[mask, code_col] = df.loc[mask, code_col].astype(str)
    # Remove trailing '.0' if present and length > 8
    df.loc[mask, code_col] = df.loc[mask, code_col].apply(lambda x: x[:-2] if len(x) > 8 and x.endswith('.0') else x)
    # Remove rows with 10-digit codes
    df = df[~((df[year_col] >= year_threshold) & (df[code_col].astype(str).str.len() >= 10))]
    # Add leading zero to 7-digit codes
    mask = (df[year_col] >= year_threshold) & (df[code_col].astype(str).str.len() == 7)
    df.loc[mask, code_col] = df.loc[mask, code_col].apply(lambda x: '0' + x)
    return df

all_mappings_1 = clean_hs_codes(all_mappings_1)

In [42]:
df_1989_onwards = all_mappings_1[all_mappings_1['from_year'] >= 1989]

df_1989_onwards["HS_N"].astype(str).str.len().value_counts()

HS_N
8    459783
Name: count, dtype: int64

In [43]:
df_1989_onwards = all_mappings_1[all_mappings_1['to_year'] >= 1990]

df_1989_onwards["Mapped_HS"].astype(str).str.len().value_counts()

Mapped_HS
8    459783
Name: count, dtype: int64

In [44]:
all_mappings_1["HS_N1"] = all_mappings_1["Mapped_HS"]

all_mappings_1

,HS_N,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1,HS_N1
0,01023100,Live purebred breeding buffalo,01023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01023100
1,01019040,Mules and hinnies not imported for immediate s...,01019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01019040
2,01031000,Live purebred breeding swine,01031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01031000
3,01022100,Live purebred breeding cattle,01022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01022100
4,01012900,Live horses other than purebred breeding horses,01012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01012900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_129_canes_walking_sticks_and_whips
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_110_playing_cards
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790,1790_138_all_coaches_chariots_phaetons_chaises_ch
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_131_brushes
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790,1790_139_all_other_goods_wares_and_merchandise

In [45]:
all_mappings_1

,HS_N,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1,HS_N1
0,01023100,Live purebred breeding buffalo,01023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01023100
1,01019040,Mules and hinnies not imported for immediate s...,01019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01019040
2,01031000,Live purebred breeding swine,01031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01031000
3,01022100,Live purebred breeding cattle,01022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01022100
4,01012900,Live horses other than purebred breeding horses,01012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01012900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_129_canes_walking_sticks_and_whips
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_110_playing_cards
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790,1790_138_all_coaches_chariots_phaetons_chaises_ch
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_131_brushes
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790,1790_139_all_other_goods_wares_and_merchandise

In [46]:
import matplotlib.pyplot as plt
import plotly.express as px

avg_similarity_by_year = all_mappings_1.groupby('from_year')['Combined_Similarity'].mean()

fig = px.line(
    avg_similarity_by_year,
    labels={'index': 'from_year', 'value': 'Average Combined Similarity'},
    title='Average Combined Similarity by from_year'
)
fig.update_traces(mode='lines+markers')
fig.update_layout(xaxis_title='from_year', yaxis_title='Average Combined Similarity')
fig.show()

In [47]:
all_mappings_1

,HS_N,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1,HS_N1
0,01023100,Live purebred breeding buffalo,01023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01023100
1,01019040,Mules and hinnies not imported for immediate s...,01019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01019040
2,01031000,Live purebred breeding swine,01031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01031000
3,01022100,Live purebred breeding cattle,01022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01022100
4,01012900,Live horses other than purebred breeding horses,01012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01012900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_129_canes_walking_sticks_and_whips
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_110_playing_cards
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790,1790_138_all_coaches_chariots_phaetons_chaises_ch
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_131_brushes
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790,1790_139_all_other_goods_wares_and_merchandise

In [48]:
# output all_mappings_1 to a pickle file called mapping_N_N1.pkl
all_mappings_1.to_pickle('NEW_mapping_N_N1.pkl')

In [70]:
# open the pickle file
df = pd.read_pickle("NEW_mapping_N_N1.pkl")
df

,HS_N,Description_N1,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1,HS_N1
0,01023100,Live purebred breeding buffalo,01023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01023100
1,01019040,Mules and hinnies not imported for immediate s...,01019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01019040
2,01031000,Live purebred breeding swine,01031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01031000
3,01022100,Live purebred breeding cattle,01022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01022100
4,01012900,Live horses other than purebred breeding horses,01012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01012900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_129_canes_walking_sticks_and_whips
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_110_playing_cards
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790,1790_138_all_coaches_chariots_phaetons_chaises_ch
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_131_brushes
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790,1790_139_all_other_goods_wares_and_merchandise

In [64]:
df_1989_onwards = df[df['from_year'] >= 1989]

df_1989_onwards["HS_N"].astype(str).str.len().value_counts()

HS_N
8    459783
Name: count, dtype: int64

In [65]:
df_1989_onwards = df[df['to_year'] >= 1990]

df_1989_onwards["HS_N1"].astype(str).str.len().value_counts()

HS_N1
8    459783
Name: count, dtype: int64

In [53]:
filtered_N1_N = pd.read_pickle('./filtered_N1_N.pkl')

In [56]:
filtered_N1_N.columns

Index(['from_year', 'to_year', 'year_N', 'year_N1', 'HS_N', 'HS_N1',
       'Cosine_Similarity', 'Jaccard_Similarity', 'Levenshtein_Similarity',
       'Combined_Similarity', 'Description_N', 'Description_N1'],
      dtype='object')

In [ ]:
# rename Description_N1 to Description_N
df.rename(columns={"Description_N1": "Description_N"}, inplace=True)

,HS_N,Description_N,Mapped_HS,Mapped_Description,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1,HS_N1
0,01023100,Live purebred breeding buffalo,01023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01023100
1,01019040,Mules and hinnies not imported for immediate s...,01019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01019040
2,01031000,Live purebred breeding swine,01031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01031000
3,01022100,Live purebred breeding cattle,01022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01022100
4,01012900,Live horses other than purebred breeding horses,01012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01012900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_129_canes_walking_sticks_and_whips
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_110_playing_cards
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790,1790_138_all_coaches_chariots_phaetons_chaises_ch
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_131_brushes
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790,1790_139_all_other_goods_wares_and_merchandise

In [72]:
df.rename(columns={"Mapped_Description": "Description_N1"}, inplace=True)

In [73]:
df

,HS_N,Description_N,Mapped_HS,Description_N1,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,from_year,to_year,year_N,year_N1,HS_N1
0,01023100,Live purebred breeding buffalo,01023100,Live purebred breeding buffalo,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01023100
1,01019040,Mules and hinnies not imported for immediate s...,01019040,Mules and hinnies not imported for immediate s...,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01019040
2,01031000,Live purebred breeding swine,01031000,Live purebred breeding swine,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01031000
3,01022100,Live purebred breeding cattle,01022100,Live purebred breeding cattle,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01022100
4,01012900,Live horses other than purebred breeding horses,01012900,Live horses other than purebred breeding horses,1.000000,1.000000,1.000000,1.000000,2022,2023,2022,2023,01012900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789_56_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1790_129_canes_walking_sticks_and_whips,"canes, walking sticks and whips",1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_129_canes_walking_sticks_and_whips
745502,1789_61_playing_cards,playing cards,1790_110_playing_cards,playing cards,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_110_playing_cards
745503,1789_62_every_coach_chariot_or_other_four_wheel,"every coach, chariot or other four wheel carri...",1790_138_all_coaches_chariots_phaetons_chaises_ch,"All coaches, chariots, phaetons, chaises, chai...",0.836723,0.120000,0.594340,0.669140,1789,1790,1789,1790,1790_138_all_coaches_chariots_phaetons_chaises_ch
745504,1789_58_brushes,brushes,1790_131_brushes,brushes,1.000000,1.000000,1.000000,1.000000,1789,1790,1789,1790,1790_131_brushes
745505,1789_63_other_goods_wares_and_merchandise,"other goods, wares and merchandise",1790_139_all_other_goods_wares_and_merchandise,"all other goods, wares and merchandise",0.942003,0.833333,0.944444,0.920513,1789,1790,1789,1790,1790_139_all_other_goods_wares_and_merchandise

In [74]:
df.columns

Index(['HS_N', 'Description_N', 'Mapped_HS', 'Description_N1',
       'Cosine_Similarity', 'Jaccard_Similarity', 'Levenshtein_Similarity',
       'Combined_Similarity', 'from_year', 'to_year', 'year_N', 'year_N1',
       'HS_N1'],
      dtype='object')

In [75]:
columns = ['from_year', 'to_year', 'year_N', 'year_N1', 'HS_N', 'HS_N1',
       'Cosine_Similarity', 'Jaccard_Similarity', 'Levenshtein_Similarity',
       'Combined_Similarity', 'Description_N', 'Description_N1']
df = df[columns]

df

,from_year,to_year,year_N,year_N1,HS_N,HS_N1,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,Description_N,Description_N1
0,2022,2023,2022,2023,01023100,01023100,1.000000,1.000000,1.000000,1.000000,Live purebred breeding buffalo,Live purebred breeding buffalo
1,2022,2023,2022,2023,01019040,01019040,1.000000,1.000000,1.000000,1.000000,Mules and hinnies not imported for immediate s...,Mules and hinnies not imported for immediate s...
2,2022,2023,2022,2023,01031000,01031000,1.000000,1.000000,1.000000,1.000000,Live purebred breeding swine,Live purebred breeding swine
3,2022,2023,2022,2023,01022100,01022100,1.000000,1.000000,1.000000,1.000000,Live purebred breeding cattle,Live purebred breeding cattle
4,2022,2023,2022,2023,01012900,01012900,1.000000,1.000000,1.000000,1.000000,Live horses other than purebred breeding horses,Live horses other than purebred breeding horses
...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789,1790,1789,1790,1789_56_canes_walking_sticks_and_whips,1790_129_canes_walking_sticks_and_whips,1.000000,1.000000,1.000000,1.000000,"canes, walking sticks and whips","canes, walking sticks and whips"
745502,1789,1790,1789,1790,1789_61_playing_cards,1790_110_playing_cards,1.000000,1.000000,1.000000,1.000000,playing cards,playing cards
745503,1789,1790,1789,1790,1789_62_every_coach_chariot_or_other_four_wheel,1790_138_all_coaches_chariots_phaetons_chaises_ch,0.836723,0.120000,0.594340,0.669140,"every coach, chariot or other four wheel carri...","All coaches, chariots, phaetons, chaises, chai..."
745504,1789,1790,1789,1790,1789_58_brushes,1790_131_brushes,1.000000,1.000000,1.000000,1.000000,brushes,brushes
745505,1789,1790,1789,1790,1789_63_other_goods_wares_and_merchandise,1790_139_all_other_goods_wares_and_merchandise,0.942003,0.833333,0.944444,0.920513,"other goods, wares and merchandise","all other goods, wares and merchandise"

In [77]:
# export df as a pickle file: NEW_filtered_N_N1.pkl
df.to_pickle('NEW_filtered_N_N1.pkl')

In [78]:
df

,from_year,to_year,year_N,year_N1,HS_N,HS_N1,Cosine_Similarity,Jaccard_Similarity,Levenshtein_Similarity,Combined_Similarity,Description_N,Description_N1
0,2022,2023,2022,2023,01023100,01023100,1.000000,1.000000,1.000000,1.000000,Live purebred breeding buffalo,Live purebred breeding buffalo
1,2022,2023,2022,2023,01019040,01019040,1.000000,1.000000,1.000000,1.000000,Mules and hinnies not imported for immediate s...,Mules and hinnies not imported for immediate s...
2,2022,2023,2022,2023,01031000,01031000,1.000000,1.000000,1.000000,1.000000,Live purebred breeding swine,Live purebred breeding swine
3,2022,2023,2022,2023,01022100,01022100,1.000000,1.000000,1.000000,1.000000,Live purebred breeding cattle,Live purebred breeding cattle
4,2022,2023,2022,2023,01012900,01012900,1.000000,1.000000,1.000000,1.000000,Live horses other than purebred breeding horses,Live horses other than purebred breeding horses
...,...,...,...,...,...,...,...,...,...,...,...,...
745501,1789,1790,1789,1790,1789_56_canes_walking_sticks_and_whips,1790_129_canes_walking_sticks_and_whips,1.000000,1.000000,1.000000,1.000000,"canes, walking sticks and whips","canes, walking sticks and whips"
745502,1789,1790,1789,1790,1789_61_playing_cards,1790_110_playing_cards,1.000000,1.000000,1.000000,1.000000,playing cards,playing cards
745503,1789,1790,1789,1790,1789_62_every_coach_chariot_or_other_four_wheel,1790_138_all_coaches_chariots_phaetons_chaises_ch,0.836723,0.120000,0.594340,0.669140,"every coach, chariot or other four wheel carri...","All coaches, chariots, phaetons, chaises, chai..."
745504,1789,1790,1789,1790,1789_58_brushes,1790_131_brushes,1.000000,1.000000,1.000000,1.000000,brushes,brushes
745505,1789,1790,1789,1790,1789_63_other_goods_wares_and_merchandise,1790_139_all_other_goods_wares_and_merchandise,0.942003,0.833333,0.944444,0.920513,"other goods, wares and merchandise","all other goods, wares and merchandise"